# Generated by Django 4.0.2 on 2024-12-13 03:38

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_profile_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_category',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, to='netflix.Category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 3, 38, 45, 404756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
