# Generated by Django 4.0.2 on 2024-12-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
