# Generated by Django 4.0.2 on 2024-12-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0006_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
